[package]
name = "vorlias/net"
description = "Advanced multi-language networking library for Roblox."
version = "3.0.7"
license = "MIT"
authors = ["Vorlias"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
